:: File:	Run_Tests.bat
:: Author:	Keegan MacDonald
:: Created:	2025.01.12@18:56
:: Purpose:	Run the NIST SP800-22 Test Suite on each of the binary files
:: 		generated by the Jabberwock PRNG library test.

@echo off

for /l %%x in (1, 1, 100) do (
	echo Generating results for test of "Data/%%x.bin"
	python sp800_22_tests/sp800_22_tests.py Data/%%x.bin >> Results/%%x.txt
)
pause